// Generated by CoffeeScript 1.8.0
(function() {
  var Model, argv, db, js2coffee;

  db = require("./mysql");

  js2coffee = require('js2coffee');

  argv = require('optimist').argv;

  Model = (function() {
    function Model(tableName) {
      this.tableName = tableName;
    }

    Model.prototype.descSql = function() {
      var self;
      self = this;
      return db.query("DESC " + self.tableName, function(err, row) {
        var code, i, tmp, _i, _len, _results;
        if (err) {
          return console.log(err);
        }
        code = [];
        _results = [];
        for (_i = 0, _len = row.length; _i < _len; _i++) {
          i = row[_i];
          tmp = {};
          tmp["name"] = i.Field;
          tmp["type"] = checkType(i.Type);
          tmp["defaultValue"] = i.Default;
          if (i.Key === 'PRI') {
            tmp["primaryKey"] = true;
            delete tmp["defaultValue"];
          }
          _results.push(code.push(tmp));
        }
        return _results;
      });
    };

    Model.prototype.checkType = function(test) {
      if (test.indexOf("int") > -1) {
        return 'T.Type.Integer';
      }
      if (test.indexOf("char") > -1) {
        return 'T.Type.String';
      }
      if (test.indexOf("decimal") > -1) {
        return 'T.Type.Float';
      }
      if (test.indexOf("text") > -1) {
        return 'T.Type.Json';
      }
      return 'T.Type.String';
    };

    Model.prototype.filterType = function(test) {
      var one, three, tow;
      one = test.replace(/"T.Type.Integer"/g, "T.Type.Integer");
      tow = one.replace(/"T.Type.String"/g, "T.Type.String");
      three = tow.replace(/"T.Type.Float"/g, "T.Type.Float");
      return three;
    };

    return Model;

  })();

}).call(this);

//# sourceMappingURL=app.js.map
