// Generated by CoffeeScript 1.8.0
(function() {
  var MYSQL;

  MYSQL = {
    host: 'localhost',
    userName: 'root',
    password: '',
    databases: 'mykar_task'
  };

  module.exports = MYSQL;

}).call(this);

//# sourceMappingURL=config.js.map
