// Generated by CoffeeScript 1.8.0
(function() {
  var config, connection, mysql;

  mysql = require("mysql");

  config = require("./config");

  connection = mysql.createConnection({
    host: config.host,
    user: config.userName,
    password: config.password,
    database: config.databases
  });

  connection.connect(function(err) {
    if (err) {
      return console.log('error connecting: ' + err.stack);
    }
  });

  module.exports = connection;

}).call(this);

//# sourceMappingURL=mysql.js.map
